[package]
name = "ez-vend-launcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
directories = "5.0"
sysinfo = "0.32"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "fs"] }
urlencoding = "2.1"
warp = "0.3"
webbrowser = "1.0"
