version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/crates/app"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
